ALTER TABLE recruiter_profiles
ADD COLUMN company_name VARCHAR(255),
ADD COLUMN city VARCHAR(100),
ADD COLUMN org_type VARCHAR(50),
ADD COLUMN website VARCHAR(255),
ADD COLUMN headline VARCHAR(255),
ADD COLUMN about TEXT,
ADD COLUMN avatar VARCHAR(255),
ADD COLUMN linkedin VARCHAR(255);
